// words.js
const LIBRARIES = {
    "Easy": [
        { index: 1, good: "Vampire", confused: "Werewolf" },
        { index: 2, good: "Zombie", confused: "Skeleton" },
        { index: 3, good: "Ghost", confused: "Demon" },
        { index: 4, good: "Witch", confused: "Fairy" },
        { index: 5, good: "Coffin", confused: "Urn" },
        { index: 6, good: "Haunted House", confused: "Graveyard" },
        { index: 7, good: "Bar", confused: "Restaurant" },
        { index: 8, good: "Night Club", confused: "Concert" },
        { index: 9, good: "Party", confused: "Wedding" },
        { index: 10, good: "Festival", confused: "Parade" },
        { index: 11, good: "Gym", confused: "Hospital" },
        { index: 12, good: "Vacation", confused: "Staycation" },
        { index: 13, good: "Hobby", confused: "Career" },
        { index: 14, good: "Side Hustle", confused: "Full-time Job" },
        { index: 15, good: "Meeting", confused: "Interview" },
        { index: 16, good: "Deadline", confused: "Appointment" },
        { index: 17, good: "Influencer", confused: "Journalist" },
        { index: 18, good: "Celebrity", confused: "Politician" },
        { index: 19, good: "Content", confused: "Advertisement" },
        { index: 20, good: "Audience", confused: "Customer" },
        { index: 21, good: "Love", confused: "Friendship" },
        { index: 22, good: "Happiness", confused: "Excitement" },
        { index: 23, good: "Lonely", confused: "Bored" },
        { index: 24, good: "Regret", confused: "Guilt" },
        { index: 25, good: "Trust", confused: "Loyalty" },
        { index: 26, good: "Lie", confused: "Joke" },
        { index: 27, good: "Secret", confused: "Surprise" },
        { index: 28, good: "Rumor", confused: "News" },
        { index: 29, good: "Compliment", confused: "Insult" },
        { index: 30, good: "Argument", confused: "Discussion" },
        { index: 31, good: "Promise", confused: "Threat" },
        { index: 32, good: "Question", confused: "Statement" },
        { index: 33, good: "Apology", confused: "Excuse" },
        { index: 34, good: "Monster", confused: "Villain" },
        { index: 35, good: "Nightmare", confused: "Horror Movie" }
    ],

    "Medium": [
        { index: 1, good: "Truth", confused: "Opinion" },
        { index: 2, good: "Fact", confused: "Theory" },
        { index: 3, good: "Memory", confused: "Imagination" },
        { index: 4, good: "Logic", confused: "Intuition" },
        { index: 5, good: "Fear", confused: "Anxiety" },
        { index: 6, good: "Confidence", confused: "Ego" },
        { index: 7, good: "Freedom", confused: "Independence" },
        { index: 8, good: "Responsibility", confused: "Obligation" },
        { index: 9, good: "Choice", confused: "Consequence" },
        { index: 10, good: "Meaning", confused: "Purpose" },
        { index: 11, good: "Passion", confused: "Obsession" },
        { index: 12, good: "Calm", confused: "Relaxed" },
        { index: 13, good: "Hope", confused: "Optimism" },
        { index: 14, good: "Stress", confused: "Panic" },
        { index: 15, good: "Pride", confused: "Satisfaction" },
        { index: 16, good: "Sarcasm", confused: "Sincerity" },
        { index: 17, good: "Pattern", confused: "Habit" },
        { index: 18, good: "Luck", confused: "Chance" },
        { index: 19, good: "Skill", confused: "Practice" },
        { index: 20, good: "Talent", confused: "Training" },
        { index: 21, good: "Intelligence", confused: "Education" },
        { index: 22, good: "Wisdom", confused: "Age" },
        { index: 23, good: "Rule", confused: "Law" },
        { index: 24, good: "Plan", confused: "Goal" },
        { index: 25, good: "Process", confused: "Result" },
        { index: 26, good: "Cause", confused: "Effect" },
        { index: 27, good: "Viral", confused: "Trending" },
        { index: 28, good: "Algorithm", confused: "Moderator" },
        { index: 29, good: "Brand", confused: "Product" },
        { index: 30, good: "Privacy", confused: "Secrecy" },
        { index: 31, good: "Fame", confused: "Respect" },
        { index: 32, good: "Attention", confused: "Curiosity" },
        { index: 33, good: "Curse", confused: "Disease" },
        { index: 34, good: "Possession", confused: "Infection" },
        { index: 35, good: "Legend", confused: "Folklore" }
    ],

    "Hard": [
        { index: 1, good: "Reality", confused: "Narrative" },
        { index: 2, good: "Identity", confused: "Reputation" },
        { index: 3, good: "Value", confused: "Worth" },
        { index: 4, good: "Power", confused: "Influence" },
        { index: 5, good: "Authority", confused: "Leadership" },
        { index: 6, good: "Control", confused: "Protection" },
        { index: 7, good: "Comfort", confused: "Luxury" },
        { index: 8, good: "Safety", confused: "Convenience" },
        { index: 9, good: "Discipline", confused: "Punishment" },
        { index: 10, good: "Motivation", confused: "Reward" },
        { index: 11, good: "Desire", confused: "Curiosity" },
        { index: 12, good: "Success", confused: "Fame" },
        { index: 13, good: "Fulfillment", confused: "Achievement" },
        { index: 14, good: "Obsession", confused: "Addiction" },
        { index: 15, good: "Authenticity", confused: "Honesty" },
        { index: 16, good: "Bias", confused: "Preference" },
        { index: 17, good: "Objectivity", confused: "Neutrality" },
        { index: 18, good: "Justice", confused: "Fairness" },
        { index: 19, good: "Morality", confused: "Ethics" },
        { index: 20, good: "Freedom", confused: "Autonomy" },
        { index: 21, good: "Self-awareness", confused: "Introspection" },
        { index: 22, good: "Consciousness", confused: "Awareness" },
        { index: 23, good: "Reality Star", confused: "Influencer" },
        { index: 24, good: "Public Image", confused: "Persona" },
        { index: 25, good: "Relevance", confused: "Popularity" },
        { index: 26, good: "Narrative", confused: "Perspective" },
        { index: 27, good: "Meaninglessness", confused: "Emptiness" },
        { index: 28, good: "Fate", confused: "Destiny" },
        { index: 29, good: "Existence", confused: "Life" },
        { index: 30, good: "Time", confused: "Moment" },
        { index: 31, good: "Chaos", confused: "Uncertainty" },
        { index: 32, good: "Order", confused: "Stability" },
        { index: 33, good: "Truthfulness", confused: "Accuracy" },
        { index: 34, good: "Reality", confused: "Perception" },
        { index: 35, good: "Self", confused: "Identity" }
    ]
};
